### ISSUE TITLE
path in object to library

### ISSUE THREAD

**Issue by sevdh** [timothyschoen/PlugData#107]
I can use Else's out~ abstraction both without the path: [out~], and with path: [else/out~].

However I cannot do the same for for example cyclone's gate. [gate] works but [cyclone/gate] doesn't work.

I think it would be nice to be able to give a specific path to an external because they sometimes share the same name.

**Comment by timothyschoen** [comment]
I'm aware of this problem, I even modify all the help files to not use the full path. The reason that it works for out~ is because it's an abstraction, while cyclone/gate is a C-coded external. Because I have to compile externals along with PlugData to get it working in a plugin, it won't find them by their full path name.

After reading up on it a bit, it looks like I can use class_addcreator to create aliases. I'm just hoping to find a way that doesn't involve manually adding these to every ELSE and cyclone object.

**Comment by sevdh** [comment]
I see, I found an exception...

What about thinking in the other direction and requiring the path for externals? The automatic suggestion of the objects helps a lot in being able to find them anyway. (I fully understand both solutions have their own pros and cons).

**Comment by timothyschoen** [comment]
I'd like to keep the short names available as it's still faster to type. The suggestions only become useful once you're at the unique part of the name, so you still have to type "cyclone/", and since ELSE and cyclone are a part of PlugData and have no naming conflicts (AFAIK?), I think it's fine this way.

I think I've found a hack to allow full names for ELSE and cyclone, so I'll add that very soon.

**Comment by timothyschoen** [comment]
I did this kinda ugly hack: I can rely on the fact that I initialise the ELSE and cyclone objects alphabetically to know which objects belong to ELSE and cyclone. Then I can create new creation methods for those objects with the correct prefix. There was one exception, cyclone/Pow~ which already had a full library name constructor (to prevent confusion with builtin pow~), so we skip that one. Works perfectly!

<img width="893" alt="Screenshot 2022-05-18 at 00 16 31" src="https://user-images.githubusercontent.com/44585538/168920982-e819c144-6536-4e3e-a1ba-1555b06825b7.png">
