### ISSUE TITLE
opening a Pure Data patch doesn't always result in the number and comment boxes to display properly

### ISSUE THREAD

**Issue by sevdh** [timothyschoen/PlugData#110]
For example:
- Number boxes are sometimes as wide as in PD
- Comment bozes sometimes appear differently or have almost no width at all (resulting in nothing being displayed)

**Comment by timothyschoen** [comment]
The comment bug is known to me, I'll see what's up with the number box as well.

The problem is that pd sometimes measures object width in (monospace) text characters, previously I directly converted it to width in pixels, but that creates some problems. Now I'm trying to do this "correctly" but there's still some cases where this doesn't work.
