### ISSUE TITLE
Can’t resize plugin window

### ISSUE THREAD

**Issue by zkf** [timothyschoen/PlugData#120]
Linux, Ardour 6. The plugin window itself does not resize even though the contents do ... I think this short video explains the issue better:

https://user-images.githubusercontent.com/613216/169658385-5732c0aa-521e-41c9-b5c0-4bd986dc80ca.mp4

**Comment by timothyschoen** [comment]
Is this also a problem for the VST3? Otherwise, I assume this will also be fixed by using JUCE 7. 

Unfortunately, JUCE 7 is not released yet, so I'm unsure if I should already make the switch. The argument for making the switch is that it probably fixes many LV2 issues and will also make it much faster on Mac, and probably a bit faster on Windows.

**Comment by zkf** [comment]
This was fixed after upgrading to the latest commit and deleting the config. Resizing is a little slow but this goes for the VST as well. Fingers crossed for JUCE 7 :)

**Comment by timothyschoen** [comment]
That's unexpected but good!
