### ISSUE TITLE
Include sfont~ from else rc2

### ISSUE THREAD

**Issue by porres** [timothyschoen/PlugData#132]

**Comment by timothyschoen** [comment]
Mostly already done, except for including sfont~. It was difficult getting it to build/link on all platforms.

Until now, I was able to supply binaries that contain everything, which will become impossible if I have to dynamically link libraries. And if I don't build/link everything in one binary, I'll have to make installers for a few different platforms and architectures.

JUCE also has an interface for reading all of these audio formats, so I'm also considering writing my own libsndfile implementation (with the same API) that uses JUCE. It will also be time-consuming to do this, but probably the cleanest solution.

**Comment by porres** [comment]
maybe just upgrade without the sfont~ file for now if it's too crazy to do that?

**Comment by porres** [comment]
how is this going? RC3 is coming around monday

**Comment by timothyschoen** [comment]
I'm planning to add this the next version, probably released in 2/3 weeks (I'll upgrade ELSE to rc2 as well).
 
I still need to look at sfont~ a bit more, I'm still unsure what strategy will work best. I guess that on Linux it's reasonably to make users install fluidsynth, but on Windows and Mac it's best to include a dynamic library. Fortunately, I just created an installer for Windows so that should make the process a lot simpler.

I also still want to look at [store] and [rec], and I want to look at some more memory leaks in ELSE. I'll make some time for that after my next release, after which the GUI features should be pretty much done.

**Comment by porres** [comment]
I guess I can hold the update to RC3 in a couple of weeks more, the new [bicoeff] GUI is not really acceptable yet

**Comment by timothyschoen** [comment]
<img width="674" alt="Screenshot 2022-07-17 at 00 06 36" src="https://user-images.githubusercontent.com/44585538/179373289-db09ebce-3d4d-4889-b8c8-e01bc7d1bfb7.png">

Some progress: it works on Mac, but the build system still needs some work.

I've decided to go for static linking, combined with the glib-free fluidsynth. I have a script that compiles libsndfile + all dependencies as static libraries, so I can compile everything into the executable. The reason for this is that dynamic linking on 3 platforms for 3 different plugin formats is an even bigger hassle.

**Comment by porres** [comment]
I guess you can go ahead and make an update release just by including this one from rc2... as rc3 might take some while now

**Comment by timothyschoen** [comment]
[sfont~] now works on all platforms! It's running without libinstpatch, and it's using the fluidsynth-sans-glib version. I might port a version at some point to make sure it has all the latest features and libinstpatch (which also depends on glib...), but for now this will do.

I did manage to get everything statically linked, so that's nice. I wouldn't recommend that for ELSE though. Glib actually can't be linked statically anymore, so using the sans-glib version is probably better for PlugData.

**Comment by timothyschoen** [comment]
Although my static linking method it could be useful for camomile-ELSE!

**Comment by porres** [comment]
> Although my static linking method it could be useful for camomile-ELSE!

Tell us more, this is something to also talk to @emviveros about. I was telling him we should try and compile Camomile-ELSE with RC2 just to test things like this

**Comment by timothyschoen** [comment]
[This makefile](https://github.com/timothyschoen/PlugData/blob/main/Libraries/ELSE/sfont%7E/make-static-libs.mk) will download and build fluidsynth and all the dependencies statically, and puts it in the folder /fluidsynth/lib and /fluidsynth/include, relative to the working directory. This works on Mac (Universal) and Linux, though I've found that sometimes on Mac, you need to run the makefile twice for it to work. I'm still investigating why.

[This zipfile](https://github.com/timothyschoen/PlugData/blob/main/Libraries/ELSE/sfont%7E/win_deps.zip) contains prebuilt static libraries for windows, and will unpack to /fluidsynth/lib, /fluidsynth/lib64 and /fluidsynth/include. You can link both the x86 and x64 versions to both, that's fine.

My cmake file looks like this:

```
# Initialise dependency list, not sure if this is necessary?
set(SFONT_LIBS "")

# Switch to enable/disable sfont~, in case the build fails or you want to speed up the build
if(ENABLE_SFONT)
    message("-- Building fluidsynth")

    set(SFONT_LIB_DIR "${CMAKE_CURRENT_BINARY_DIR}/fluidsynth/")

    if(MSVC)
        # Building fluidsynth on Windows is a hassle, so I've prebuilt all the static deps once, shipped in a zipfile
        execute_process(
            COMMAND ${CMAKE_COMMAND} -E tar xzf ${CMAKE_CURRENT_SOURCE_DIR}/ELSE/sfont~/win_deps.zip
            WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
        )

        list(APPEND SFONT_LIBS
            ${SFONT_LIB_DIR}/lib64/FLAC.lib
            ${SFONT_LIB_DIR}/lib64/libfluidsynth.lib
            ${SFONT_LIB_DIR}/lib64/libmp3lame-static.lib
            ${SFONT_LIB_DIR}/lib64/libmpghip-static.lib
            ${SFONT_LIB_DIR}/lib64/mpg123.lib
            ${SFONT_LIB_DIR}/lib64/ogg.lib
            ${SFONT_LIB_DIR}/lib64/opus.lib
            ${SFONT_LIB_DIR}/lib64/sndfile.lib
            ${SFONT_LIB_DIR}/lib64/vorbis.lib
            ${SFONT_LIB_DIR}/lib64/vorbisenc.lib

            ${SFONT_LIB_DIR}/lib/FLAC.lib
            ${SFONT_LIB_DIR}/lib/libfluidsynth.lib
            ${SFONT_LIB_DIR}/lib/libmp3lame-static.lib
            ${SFONT_LIB_DIR}/lib/libmpghip-static.lib
            ${SFONT_LIB_DIR}/lib/mpg123.lib
            ${SFONT_LIB_DIR}/lib/ogg.lib
            ${SFONT_LIB_DIR}/lib/opus.lib
            ${SFONT_LIB_DIR}/lib/sndfile.lib
            ${SFONT_LIB_DIR}/lib/vorbis.lib
            ${SFONT_LIB_DIR}/lib/vorbisenc.lib
        )
    else()
        # Build fluidsynth and dependencies from source, silence the makefile
        execute_process(COMMAND make -f ${CMAKE_CURRENT_SOURCE_DIR}/ELSE/sfont~/make-static-libs.mk config
            WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
            OUTPUT_QUIET
            #ERROR_QUIET
        )
        list(APPEND SFONT_LIBS
            ${SFONT_LIB_DIR}/lib/libfluidsynth.a
            ${SFONT_LIB_DIR}/lib/libsndfile.a
            ${SFONT_LIB_DIR}/lib/libogg.a
            ${SFONT_LIB_DIR}/lib/libopus.a
            ${SFONT_LIB_DIR}/lib/libFLAC.a
            ${SFONT_LIB_DIR}/lib/libvorbis.a
            ${SFONT_LIB_DIR}/lib/libvorbisenc.a
        )
    endif()

    # Check if build succeeded, otherwise disable sfont
    foreach(LIB ${SFONT_LIBS})
        if(NOT EXISTS ${LIB})
            set(FAILED_LIBS ${FAILED_LIBS} ${LIB})
            set(ENABLE_SFONT 0)
        endif()
    endforeach()

    if(FAILED_LIBS)
    message("Error building fluidsynth: Libraries not found:")
    foreach(LIB ${FAILED_LIBS})
        message(${LIB})
    endforeach()
    message("Disabling sfont object")
    endif()
endif()

if(ENABLE_SFONT)
    # Enable compilation of sfont~
    list(APPEND ELSE_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/ELSE/sfont~/sfont~.c)

    # Add fluidsynth include dir
    include_directories(${PROJECT_BINARY_DIR}/fluidsynth/include)

    # add macro definition
    # you'll need to put the sfont_tilde_setup() part (2x) in a macro if statement, based on whether sfont~ is enabled
    list(APPEND LIBPD_COMPILE_DEFINITIONS ENABLE_SFONT=1)
endif()

if(MSVC)
target_link_libraries(insert_target_here Shlwapi.lib ${SFONT_LIBS}  ... insert other libs )
else() 
target_link_libraries(insert_target_here ${SFONT_LIBS}  ... insert other libs )
endif()
``` 

Hope that helps, let me know if you need more help

**Comment by porres** [comment]
why? I dont even know what you're talking about :)

**Comment by timothyschoen** [comment]
At the end of this thread: https://github.com/timothyschoen/PlugData/issues/115

All that has changed is that I put a zipped version of all the projects for fluidsynth, sndfile, libogg etc. in the repo, instead of downloading those. This makes sure it can be built on SUSE's servers.

You can either use the download or zip method, it doesn't really matter, but I thought I would warn you in case you/@emviveros start working on Camomile-ELSE and get confused because it has changed since this thread.

**Comment by emviveros** [comment]
Thanks @timothyschoen for all.

I'm starting to include ELSE rc2 right now and I can barely understand what's happening with devops issues. I will ask here since structured question start.

**Comment by timothyschoen** [comment]
I've created a fork of Camomile and added the latest ELSE+sfont to it, it was easier to do it that way because the original Camomile uses cmake for its builds. Also, you have an older submodule of libpd in your project that uses the "git://" prefix instead of "https://", which is no longer allowed. This causes cloning your git repo to fail.

It might be a bit more difficult to merge our repos, I suggest you do it manually by copying the Source folder and cmakelists.txt from my project into your project. You can also clean up all the Projucer projects and makefiles if you like.

I still need to do some testing but I think this will work!

https://github.com/timothyschoen/Camomile

**Comment by timothyschoen** [comment]
I've also updated JUCE and Pd, so if there's a way you can copy the whole repository, that would probably be better. Also, I realised that by only copying sources and the cmakelist, we still don't fix the broken libpd url.

**Comment by emviveros** [comment]
Ok... I'm inclined to copy your repository. But first I don't know how to compile Camomile with your repository. How can I do it?

**Comment by timothyschoen** [comment]
```
git clone --recursive https://github.com/emviveros/Camomile-ELSE.git
cd Camomile-ELSE
mkdir build && cd build
cmake .. (the generator can be specified using -G"Unix Makefiles", -G"XCode" or -G"Visual Studio 16 2019" -A x64)
cmake --build .
```

I see there are still some small problems with Linux and x64 Windows, I'll see if I can fix that.

**Comment by emviveros** [comment]
Awesome! I'm dreaming with compiling it in this way. Do you know some documentation that I can learn how to do it with github actions?

**Comment by timothyschoen** [comment]
I can explain a bit. The most important file is located at `.github/workflows/cmake.yml`. This contains scripts with build instructions for each OS. If you copy my changes in, it should automatically detect the file, and start compiling everything on Github's servers. In the "Actions" tab of your repo, you can see the progress and download the files once it's done.


https://docs.github.com/en/actions/learn-github-actions might help as well.

**Comment by emviveros** [comment]
I'm trying to compile from your repository in Mac and I can't see where the compiled vst files are.. I have:
```
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building fluidsynth
Error building fluidsynth: Libraries not found:
/Users/esteban/Compilation/TESTE_de_compilação/Camomile/build/fluidsynth/lib/libfluidsynth.a
/Users/esteban/Compilation/TESTE_de_compilação/Camomile/build/fluidsynth/lib/libsndfile.a
/Users/esteban/Compilation/TESTE_de_compilação/Camomile/build/fluidsynth/lib/libogg.a
/Users/esteban/Compilation/TESTE_de_compilação/Camomile/build/fluidsynth/lib/libopus.a
/Users/esteban/Compilation/TESTE_de_compilação/Camomile/build/fluidsynth/lib/libFLAC.a
/Users/esteban/Compilation/TESTE_de_compilação/Camomile/build/fluidsynth/lib/libvorbis.a
/Users/esteban/Compilation/TESTE_de_compilação/Camomile/build/fluidsynth/lib/libvorbisenc.a
Disabling sfont object
-- Configuring juceaide
-- Building juceaide
-- Exporting juceaide
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/esteban/Compilation/TESTE_de_compilação/Camomile/build
```

**Comment by timothyschoen** [comment]
Did you run cmake with or without "-GXcode"?

Thing I see it that sfont is not compiling on your machine. We'll find out soon why but for now it's fine, it will automatically disable it. It is very strange because it does build on Github's macOS runner and on my machine.

You have now configured your cmake project. Now you have two options, either find the .xcodeproj in the Build folder and use that, or run ```cmake --build . ```.

**Comment by emviveros** [comment]
I was make: ```cmake .. -GXcode```

Now I tried ``cmake --build``` but comilation lailed in sfont~

```
** BUILD FAILED **


The following build commands failed:
	CompileC build/Camomile.build/Debug/Camomile.build/Objects-normal/x86_64/sfont~.o Source/Pd/ELSE/sfont~/sfont~.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
