### ISSUE TITLE
Spinning beachball when loading raw data into a table

### ISSUE THREAD

**Issue by vewilya** [timothyschoen/PlugData#137]
Whenever I am trying to load raw data into a table, PlugData starts having on/off episodes of the spinning beachball until it crashes eventually. Vanilla PD has no issues with the same patch or with the files that I am trying to load in.

<img width="403" alt="Screenshot 2022-06-23 at 15 59 24" src="https://user-images.githubusercontent.com/77921468/175318396-235ffe29-29ea-4107-b95d-0468d6d3375b.png">

**Comment by timothyschoen** [comment]
Thanks for reporting, what version are you using?

**Comment by vewilya** [comment]
I'm on 0.5.3... Just built it again this morning. 🖖, Urs

**Comment by timothyschoen** [comment]
I can reproduce this, it's caused by the enormous load that's created when drawing anything that's more than a few kb in size. pd-vanilla is stunningly fast with this, I was really surprised to see it can handle very large files effortlessly.

I'm going to look into drawing it to an image, that's probably the way to go.

Testing this also made me find a bug, the array now properly resizes, which is previously didn't.

Nice seeing you here Urs, I didn't realise it was you!

**Comment by timothyschoen** [comment]
Turns out it was pretty simple, I shouldn't draw more data points than the pixel width of the graph, at the point it doesn't improve the graph and it becomes very expensive. Doing this makes the content look more similar to what Pd shows as well!

Thanks again for reporting this, I think this is a huge improvement!

**Comment by vewilya** [comment]
Awesome Tim! Thx for pushing a fix that quickly! 🙏💪
