### ISSUE TITLE
Strange calculations with playhead and file path misread

### ISSUE THREAD

**Issue by Omar-Misa** [timothyschoen/PlugData#150]
Pictured here is a strange result in a calculation.  The same happens when using [expr] and other mathematical operators.  When i hit the bang, however, the result is accurate:
![calculations](https://user-images.githubusercontent.com/72618091/177411164-166016bd-e649-425d-aec1-6b98eb6001df.PNG)

Another issue is with symbol returned from [openpanel].  i believe it's a Windows thing.  The returned symbol demarcate the file path hierarchy with a backslash.  i believe backslash is interpreted as spaces.  Using forward-slashes works as expected.

PlugData v0.5.3 VST3, Win10

**Comment by timothyschoen** [comment]
Thanks for reporting, I'll see what's causing this!

I didn't consider the backslashes, I'll look into that as well.

**Comment by timothyschoen** [comment]
Good to know, that narrows it down quite a lot.

**Comment by timothyschoen** [comment]
This is because the output of playhead position is actually a list with 3 items! I copied this from Camomile so I didn't notice it myself yet. The solution is to put an [unpack f f f] underneath it, and you can now also get time in samples if you want! And calculation behave normally again!

I've also fixed openpanel on Windows!

**Comment by Omar-Misa** [comment]
Thank you!  Glad that playhead-position use is so simply solved.
Thanks too, more broadly, for making and sharing PlugData!
