### ISSUE TITLE
projects that used 0.5.3 are not loading the plugin using the recent builds

### ISSUE THREAD

**Issue by offthesky** [timothyschoen/PlugData#153]
i installed the latest build Commit [a46b2be](https://github.com/timothyschoen/PlugData/commit/a46b2be40a6b8e39c42360bbe0678c9c81c1e8a1) and removed the old version (0.5.3). now any time loading up a project containing anything done with 0.5.3, both daws are complaining the plugin is missing.  tested in both ableton and reaper x64.

**Comment by timothyschoen** [comment]
Yes, this is unfortunately a thing. Since oversampling was added, I need to store it in the plugin state, so that makes the plugin incompatible with old projects. I did also changed the ID of the plugin, so at least it won't cause a crash. For now, make sure you store .pd patches of stuff you make. I'll start providing support for legacy versions from the first beta version. I'm hoping I won't have to break compatibility anymore in the future.

Sorry if this has caused problems, I'd recommend reinstalling 0.5.3 and exporting the pd patches.
