### ISSUE TITLE
Some small issues before 0.6 release

### ISSUE THREAD

**Issue by 60-hz** [timothyschoen/PlugData#164]
Hi! Here is some small issues and remarks I found in last PlugData 0.53:
- Copy/paste/cut menu is displayed on run mode only but should be available in Edit mode
- Object box should have a min width like message have
- Right clic on a pd object on "edit mode" show open, could also be available in "run mode"
- List atom should be wider when created and maybe display a 2 element « 0 » so we immediately notice it’s a listbox
- Shortcut should follow the first letter « name » like « o » for object and « n » for number… and have "l" for list box?

**Comment by timothyschoen** [comment]
You've done it again :)

All valid issues, I'll get these sorted out immediately.

And I don't know how I could've missed the copy/paste bug... wow.

**Comment by timothyschoen** [comment]
I'm only not sure about the keyboard shortcuts yet. The current keyboard shortcuts follow Max, basically because I believe that having some sort of association between the letter and the object helps to memorize the shortcut. Every time I don't use Pd for a while, It's like, Cmd + ... uuuh 3? No, 2! 

So I agree that setting them to the first letter of the object even more memorable, but at the same time I don't like to deviate from both Max and Pd... I'm also considering using Pd's shortcuts anyway, not because I like it, but because many PlugData users also use pd-vanilla and it's annoying to have to switch between shortcuts.

I'll add "l" for listbox, that seems like a good idea. I'll create a new issue to discuss the best way to handle keyboard shortcuts, because it's valuable to hear some different opinions on this. Adding "Max-like" and "Pd-like" shortcut presets to the settings dialog is also an option.

**Comment by timothyschoen** [comment]
All done except for the shortcuts, which I'll be changing in the next version
