### ISSUE TITLE
Can't make multiple connections from an outlet

### ISSUE THREAD

**Issue by DavidJameson** [timothyschoen/PlugData#17]
If I connect object A to object B, I can't connect object A to some other object C. It seems that once there is a single connection, there seems to be no way to click on the port again to start making another connection

**Comment by timothyschoen** [comment]
I assume you're using the latest release version, not the latest commit? This was indeed a problem, I had just made connections clickable that release and this was a bit of an oversight. It should be fixed with if you build the latest version. 

I'm working on a new release, but it's taking a bit longer because I really want to make sure it doesn't have any silly bugs (like this one) anymore.

**Comment by DavidJameson** [comment]
How can I reach out to you directly?

**Comment by timothyschoen** [comment]
You can mail me: timschoen123@gmail.com

**Comment by DavidJameson** [comment]
I built with the latest source and it works now
