### ISSUE TITLE
Fluidsynth compilation sometimes fails on macOS

### ISSUE THREAD

**Issue by shakfu** [timothyschoen/PlugData#173]
Awesome project, thanks for sharing!

I just tried to compile PlugData using current main branch on macOS Catalina. When I do `cmake --build .` I get an error:

```
...
[ 44%] Building CXX object CMakeFiles/PlugDataStandalone_Standalone.dir/Libraries/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.o
make[2]: *** No rule to make target `Libraries/fluidsynth/lib/libfluidsynth.a', needed by `/Users/sa/Downloads/src/PlugData/Plugins/Standalone/PlugData.app/Contents/MacOS/PlugData'.  Stop.
make[1]: *** [CMakeFiles/PlugDataStandalone_Standalone.dir/all] Error 2
make: *** [all] Error 2
```

Do I have to install fluid synth via homebrew as `brew install fluidsynth`?

**Comment by timothyschoen** [comment]
The easiest way to fix this is by passing “-DENABLE_SFONT=0” to cmake. I’m curious why it’s not working though…

**Comment by shakfu** [comment]
Thanks very much, the disable option worked.

If I have any further info why compiling [sfont~] didn't work, I'll post here.

**Comment by timothyschoen** [comment]
It looks like libopus.a actually does get built right? It's not longer in the list of failed libs. It just doesn't continue after opus returns an error. You could try putting "|| 1" at the end of line 64 of ./Libraries/ELSE/sfont~/make-static-libs.mk, like this:

``` (cd $(working_dir)/$(opus_version) && CFLAGS=$(FLAGS) ./configure $(config_options) --disable-rtcd --disable-extra-programs --disable-doc && make all install) || 1 ```

That will make sure that it will continue even if opus returns an error. 

I suspect this is because of differences between Catalina and Big Sur/newer, because it does build on GitHub's servers.

**Comment by timothyschoen** [comment]
You could also try clearing the build folder and starting again, now that you've got the sdkpath thing fixed. It might help.

**Comment by timothyschoen** [comment]
Closing this issue because this is probably related to building on macOS Catalina, and can be solved by using the -DENABLE_SFONT flag.

**Comment by chee** [comment]
btw i am experiencing this very same issue building on Monterey.

both of them.

fails at libogg unless i `export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)`, and if i do that it fails at libopus.

so i'm not sure it is to do with Catalina, but it might be due to something both shakfu and i have done to our computers

**Comment by chee** [comment]
`cmake -DENABLE_SFONT=0 ..` works, but... i'd quite like to use the `sfont~` object

**Comment by shakfu** [comment]
@chee are you, like me, running Homebrew on your Mac?

**Comment by chee** [comment]
> @chee are you, like me, running Homebrew on your Mac?

i use MacPorts for installing packages!

**Comment by shakfu** [comment]
Hi @chee 

> i use MacPorts for installing packages!

Ok, then perhaps it's not related to package manager idiosyncrasies.

I would also like to use the sound font object somehow...

**Comment by chee** [comment]
@shakfu oh, are you on an M1 mac?

**Comment by shakfu** [comment]
@chee, I'm on an intel mac

I tried to build again yesterday (this using `cmake -G "Xcode" ..` and had the same negative result as above.
