### ISSUE TITLE
Abstractions in tabs are not saved when pressing Save Project

### ISSUE THREAD

**Issue by ludnny** [timothyschoen/PlugData#61]
To reproduce:

- New project
- Create an object "inlet"
- SaveAs: Abstraction.pd
- New project
- SaveAs: Main.pd (in the same folder as Abstraction.pd)
- Create new object: "Abstraction"
- Right Click to open the object Abstraction in a new tab
- Add a Vertical Slider (or any object)
- Press Save
- Close PlugData
- Menu "Save Changes?": Save
- Start PlugData
- Open Main.pd
- Right Click to open the object Abstraction in a new tab
- The changes (Vertical Slider object) have not been saved

Tested on 4.0.2 Win64 Standalone

**Comment by timothyschoen** [comment]
This is related to #52, PlugData currently sees one patch as the root patch and only saves changes to that patch. This works fine for subpatchers because they are embedded, but it won't save abstractions. The root patch is recognisable because it has no "close tab" button. I'm going to change this, but since it'll be a lot of work I'm focussing on other problems first.

**Comment by timothyschoen** [comment]
Should be fixed
