### ISSUE TITLE
Linux min version ?

### ISSUE THREAD

**Issue by jyg** [timothyschoen/PlugData#8]
Hi,
Thanks for this awesome project !
I cannot load the VST plugin / standalone version on my  linux system
Ubuntu 18.04.6 LTS
Is there a required minimal OS version ?

**Comment by timothyschoen** [comment]
I don't think there is a minimum requirement option for Linux, so that's probably not the issue. Did you build it yourself or use the prebuilt version? I'll install Ubuntu 18.04 in a VM and test it out.

 I'm planning to make a new release tonight and send it over to some people to make sure it works for everyone, would you be interested in trying it?

**Comment by jyg** [comment]
> I don't think there is a minimum requirement option for Linux, so that's probably not the issue.

I thought this could be the issue because it was the case once with camomile earlier versions. See following discussion: https://github.com/pierreguillot/Camomile/issues/222#issuecomment-832110718 

> Did you build it yourself or use the prebuilt version? 

No, I used the prebuilt version. However, I have to further investigate.

> 
> I'm planning to make a new release tonight and send it over to some people to make sure it works for everyone, would you be interested in trying it?

Yes, of course.  thanks.

**Comment by timothyschoen** [comment]
Oh that's the same issue for sure, thanks for sharing! I do wonder how Camomile handles this currently, in the thread it says 

"PS Does this mean that we may have to distribute 2 plugin versions, according to linux OS version ?
Yes, because Ubuntu 20 and 18 are not compatible..."

But I only see one Linux plugin in the last Camomile release?

**Comment by jyg** [comment]
running PlugData standalone from command line, I get : 
`./PlugData: /lib/x86_64-linux-gnu/libm.so.6: version "GLIBC_2.29" not found (required by ./PlugData)`

**Comment by timothyschoen** [comment]
Thanks, that's a great solution I hadn't considered yet

**Comment by jyg** [comment]
However, I see two linux targets (ubuntu-18_04-build and ubuntu-20_04-build) in the file
https://github.com/pierreguillot/Camomile/blob/dev/v1.0.8/.github/workflows/cmake.yml
But this is beyond my skills :-)

**Comment by timothyschoen** [comment]
I noticed this as well which is why I copied Camomile's GitHub action. You should be able to download the build for 18.04 here:

I just pushed this so I'm going to test it myself right now.

https://github.com/timothyschoen/PlugData/actions/runs/1669201880

**Comment by timothyschoen** [comment]
Hmm I'm not sure you can access these! Just a sec..

**Comment by timothyschoen** [comment]
Build for Ubuntu 18.04, if this works for you I'll include it in the next release

https://drive.google.com/file/d/1LAiBX2L4IaB4gs2LEB4ju0nN3J70SjuH/view?usp=sharing

**Comment by jyg** [comment]
ok. Could open the standalone version on my system. Thanks !
______________________________________________________________________
![image](https://user-images.githubusercontent.com/1431894/148608104-41373451-a68c-4f16-acec-1e5cf3282a03.png)

**Comment by timothyschoen** [comment]
Thanks for confirming, I'll consider it fixed!
