### ISSUE TITLE
Symbol not found: _error when used in plugin host on macOS

### ISSUE THREAD

**Issue by mathiasbredholt** [timothyschoen/PlugData#90]
I am unable to use the fftease plugins when using PlugData within a plugin host (VST3 in Bitwig on macOS)
```
/Users/mathias/Library/PlugData/Library/Deken/fftease/pvtuner~.pd_darwin: dlopen(/Users/mathias/Library/PlugData/Library/Deken/fftease/pvtuner~.pd_darwin, 10): Symbol not found: _error
  Referenced from: /Users/mathias/Library/PlugData/Library/Deken/fftease/libfftease.pd_darwin.dylib
  Expected in: flat namespace
 in /Users/mathias/Library/PlugData/Library/Deken/fftease/libfftease.pd_darwin.dylib
```
It works fine in standalone mode. It seems to be a problem with some library related to `dl` not being linked when compiling as VST3. I have succesfully used pvtuner~ in the PlugData VST3 by manually adding the object to libpd and compiling the VST3.

**Comment by FlachyJoe** [comment]
Hi,
it's a known bug : #34

**Comment by timothyschoen** [comment]
Yeah sorry, C-coded externals in the plugin version are not working, and probably won't work for a long time because it's a limitation of pd. There are some global variables that externals depend on, that needed to be modified in order for it to work correctly as a plugin which needs multiple instances of pd, unlike the standalone. This also affects Camomile.

**Comment by mathiasbredholt** [comment]
@timothyschoen I see, sorry for not checking for the existing issue :)

**Comment by timothyschoen** [comment]
No problem, [happens to me as well](https://github.com/pure-data/deken/issues/263)
