### ISSUE TITLE
Suggestion for message box!

### ISSUE THREAD

**Issue by jaffasplaffa** [timothyschoen/PlugData#94]
Hey :)

These are not a super important suggestions, but I think it would be nice anyhow.

For the message box, it would be nice to be able to easier distinguish a message box from a number box, so they look a bit more different.

Also when you push the message box, you get no notification that the box has been pushed. In original PD, when you push a message button with the mouse, the message box kind of highlights the outer edges with black, so it's more clear it has been pushed.

But yeah, small thing...... :)

**Comment by timothyschoen** [comment]
I noticed the lack of feedback on the message object, that really needs to be fixed.

I used to have a gradient on the message box to distinguish it, but I thought it looked kinda ugly and didn't fit in with the rest of the design. I'd like to make it more different, but I'm not sure how to do it and also make it look good, if anyone has any idea, send me a drawing or quick photoshop so I get the idea!

**Comment by 60-hz** [comment]
Here is a quick color ideas made with photoshop that keeps things clear: blue is only for inlet/outlets and the rest is a simple level of gray.

- The messages / atom boxes are slightly darker than objets
- Radio's selected button are gray
- Sliders are more simple (the dark part is removed)

![white](https://user-images.githubusercontent.com/5449719/167696703-b62b42a5-e1e1-4dc3-b4f3-3168ca8890eb.jpg)
![black](https://user-images.githubusercontent.com/5449719/167696732-4786d9aa-9b14-4ede-a9a1-258e9fa73249.jpg)

**Comment by 60-hz** [comment]
Also, making a specific color declination for white and black themes might lead to many issues (currently, the switch have still many inconsistencies. Therefore, I would suggest to simple "reverse" the white mode.

Here it is from my white exemple (of course you should keep the blue colors):

![black2](https://user-images.githubusercontent.com/5449719/167699694-b24681c6-9b4c-452a-ac35-2ad72f01108e.jpg)

**Comment by timothyschoen** [comment]
Thanks, this is fantastic!! I'll keep the outlines, I think you painted over that by accident? It makes things more easily distinguishable. But I really like how smooth and clear it looks like this! I'll miss the coloured arrow in the number box a little bit, but nonetheless I think this is an improvement.

Soon I'll also add the option to set custom colours for the dark and light theme, and also a custom font option. This will help accessibility as well.

**Comment by 60-hz** [comment]
>I'll keep the outlines, I think you painted over that by accident?
If you meant small pixels around gray triangles then yes, there are not supposed to be visible in the concept since they would add somewhat useless information to new users.
I always think think the less is the better ;)

**Comment by timothyschoen** [comment]
To make sure that it fits within the colour scheme and has some consistency, I've decided that the "flag" for atoms and messages is now the same colour as the box outline (meaning the outline won't be visible there, which is also nice), and the background colour for these objects is now the same as the toolbar colour. I used a slightly lighter colour than you did because I don't want to use more shades of grey, and it also has a better contrast with the text.

<img width="426" alt="Screenshot 2022-05-10 at 23 24 14" src="https://user-images.githubusercontent.com/44585538/167724316-bd750d8c-05e1-424f-bdaa-586759964ac0.png">

**Comment by 60-hz** [comment]
Great ;)
You might also set all the font to the same color (currently font are black for obj & nbx, grey for msg and atom boxes).

**Comment by timothyschoen** [comment]
Didn't even notice, I'll fix that!

What about toggles? If I'm being consistent, I shouldn't use the blue colour in the GUI objects anymore. Should I use text colour for the on-state? Using two varying shades of grey isn't clear enough I'm affraid:

![Screen Recording 2022-05-10 at 23 39 53](https://user-images.githubusercontent.com/44585538/167726452-8eb256ae-81fe-40f9-a675-0752ae64f93c.gif)

**Comment by 60-hz** [comment]
I think you'll need a third level of grey then, yes. But doing a quick and dirty simulation of darker "activated" states is not shocking:
![white2](https://user-images.githubusercontent.com/5449719/167730138-e748510b-981b-4d5c-9ee1-f8c6a47eaea4.jpg)

**Comment by ludnny** [comment]
> What about toggles? 

Hum... for toggles, no cross for off-state is less confusing, by far ;)
Especially if you start to have multiple colour layouts, dark/light modes...

I understand how that could help beginners, but remember, as beginners, we always click everywhere to see what everything does.

An example of Toggle in VVVV:
![45](https://user-images.githubusercontent.com/46849877/167730819-ed986a95-c6fe-4e24-bb93-591f0c9d3fd4.gif)
I like how the non-filled square is an invitation to click ;)

(and the non-filled square helps to catch the difference with Bangs, the same but with circle shape)

**Comment by timothyschoen** [comment]
I'm a bit unsure about this because I really like the look of the X personally... but since you and @60-hz seem to agree on this, it might be better to make it a rectangle. It actually used to be a rectangle in early versions as well.

**Comment by timothyschoen** [comment]
<img width="381" alt="Screenshot 2022-05-11 at 02 03 28" src="https://user-images.githubusercontent.com/44585538/167743574-d9dd7fdd-656b-4609-b5dc-c40847405bd0.png">

This is what I have now! The outline thickness is also more consistent now.

**Comment by ludnny** [comment]
> This is what I have now!

Love it! Thanks!

**Comment by 60-hz** [comment]
> This is what I have now!

Yes, congrat it looks nice! But let's hope that making all gui's consistent and turning all Gui's background light grey would not reduce the contrast too much. You can keep black font maybe to keep a perfect readability.

**Comment by 60-hz** [comment]
Also since we are here, I think the yellow color for signal object and inlet/outlet is too light and should be orange for a better contrast (and it's the opposite chromatic of blue).

For a perfect pedagogic tools, you can have greyed color for locked mode and colored path + inlet/outlet for Unlocked mode (Edit) like:

Unlocked:
![unlocked](https://user-images.githubusercontent.com/5449719/167820575-85cb2d2a-4c00-4711-bfc8-10d7143d4239.jpg)

Locked:
![locked](https://user-images.githubusercontent.com/5449719/167821363-ddaf63a3-88ff-45d9-9d36-63a0e593a7e6.jpg)

**Comment by timothyschoen** [comment]
That's a pretty good idea, the orange does look a bit intense but maybe that's good.

I'm wondering though, if grey is locked and coloured is unlocked, how do we differentiate between selected and unselected cords? I do like this idea because the dots on the background are still hard to see (especially if you don't have perfect sight), but making them easier to see makes it look ugly. This could provide some very clear feedback about the lock/unlock state .

**Comment by 60-hz** [comment]
Also, another small detail but I think that the inlet / outlet "balls" that exceeds the contours of boxes should always kept half, unless there is a specific meaning  to that different inlet/outlet representation.

**Comment by timothyschoen** [comment]
I think I get what you mean, you mean I should use the image of the "Connected" state at all times except when mouse-overing? I definitely see why that could be nice.

In Max, it does show the whole ball but with a lot of transparency and no outline, maybe that could be a good solution? I could also hide them, I'll try both and see what works best!

<img width="138" alt="Screenshot 2022-05-11 at 17 02 52" src="https://user-images.githubusercontent.com/44585538/167882681-c44e622f-363a-4776-9ea1-b80d65985fe5.png">

Further in the future I want to add an option to use "line" inlets/outlet like in pd-vanilla. They'll probably look and act more like purr-data's inlets and outlets. I'm not sure yet because it's a big change code-wise (the positioning code will also need to be changed), but I find that in some cases it would work better, and I'm sure some vanilla users will prefer it.

**Comment by 60-hz** [comment]
> you mean I should use the image of the "Connected" state at all times except when mouse-overing?

Exactly!

> Further in the future I want to add an option to use "line" inlets/outlet like in pd-vanilla. 

Ok, I can understand. Maybe you have a "roundness" parameters or style on the Juice class list so you don't have to write many line of code later for that. Also, maybe using a line for a squared shape, and change ["The type shape to use for the ends of lines."](https://docs.juce.com/master/classPathStrokeType.html#a9050e37133047ab699b44b704e4f96cf)

**Comment by timothyschoen** [comment]
It's not that simple unfortunately, I could just replace the DrawEllipse with DrawRectangle, which is the easy part. But I'm convinced this will only really look good if the lines are positioned like they are in pd: all the way at the ends of the object. I realise now that I have a margin value somewhere, so maybe this isn't that hard after all. But I'm going to focus on making the default style really good before adding such options.

**Comment by 60-hz** [comment]
As for the empty squared toggle, even If I like the simplicity of the idea, I wonder if it would not be too close to a bang when no one are hit and they are closed to each other...

![difference](https://user-images.githubusercontent.com/5449719/167898464-9a84d923-4189-4d1a-9201-4c9bb89bc9b3.jpg)

**Comment by timothyschoen** [comment]
Never mind, I think I'll tweak the blue colour until the inverse it's acceptable.

**Comment by timothyschoen** [comment]
> As for the empty squared toggle, even If I like the simplicity of the idea, I wonder if it would not looks like a bang in their default state... maybe the cross is the best because of this.
> 
> ![difference](https://user-images.githubusercontent.com/5449719/167898464-9a84d923-4189-4d1a-9201-4c9bb89bc9b3.jpg)

I could reduce the rounding to make it less ambiguous, or go back to X, not sure what is better.

**Comment by timothyschoen** [comment]
> As for the empty squared toggle, even If I like the simplicity of the idea, I wonder if it would not looks like a bang in their default state... maybe the cross is the best because of this.
> 
> ![difference](https://user-images.githubusercontent.com/5449719/167898464-9a84d923-4189-4d1a-9201-4c9bb89bc9b3.jpg)

The cross is also more similar to what pd has, so it might make some patches look more like their pd counterparts as well.

**Comment by timothyschoen** [comment]
<img width="535" alt="Screenshot 2022-05-14 at 21 28 55" src="https://user-images.githubusercontent.com/44585538/168445787-84a5b024-57f8-4d0b-a21c-0db5e37788c0.png">

Redesign of GUI objects is done! Also redesigned the keyboard to fit in with the style of the rest of the objects. Message object now also has a mouse-down animation.

I'll still make the disabled X less visible.

**Comment by timothyschoen** [comment]
<img width="203" alt="Screenshot 2022-05-18 at 00 39 16" src="https://user-images.githubusercontent.com/44585538/168923861-6d7e7b4c-71fb-4792-8084-7b33c3d81c24.png">

I'm afraid the new slider design doesn't really communicate "slider" as much as "big empty box" when the value is set all the way to zero. I like the minimalism but I think this is suboptimal, I'm not sure how to make it better though... Any of you have an idea?

**Comment by 60-hz** [comment]
Vanilla "hslider" has a little bar and a "gap" on both ends.

![Capture d’écran 2022-05-18 à 09 34 04](https://user-images.githubusercontent.com/5449719/168988537-6665a956-b0f5-4ffd-a19a-e19b0c29f5b7.png)

I guess it's not a big deal to accept that logic here, and leave like 2 pixels when the value is set all the way to zero?

Also, since you extended the grey background logic to every GUI  for "consistency", you might need to have a darker grey color to keep contrast ok while zooming out.

![slider](https://user-images.githubusercontent.com/5449719/168989555-4a1048e6-b3b8-41cd-b19d-80f1a623aa17.jpg)

Finally, I think you could grey the inlet/outlet  when the patch is locked (or "runmode") and maybe also remove them from GUI's to keep the GUI's clean.

Locked :
![slider-locked](https://user-images.githubusercontent.com/5449719/168991919-a0005dfa-a501-471f-acad-eb6b71c90ff7.jpg)

**Comment by timothyschoen** [comment]
The borders look great, instantly makes it clear. Thanks for the example!

I like greying them out more I think, it really communicates "this is a thing but you can't use it now" vs "there's nothing here". For a clean, GUI-oriented experience you can use presentation mode.
